# Common label to be applied
commonLabels:
  variant: staging

namespace: roar-staging

# List of resource files that kustomize reads, modifies
# and emits as a YAML string
resources:
- ./db
- ./web
- namespace.yaml

# Generate a configmap of database info
configMapGenerator:
  - name: mysql-db-configmap
    literals:
      - mysql.database=registry_test




          
