apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: roar-db
spec:
  template:
    spec:
      containers:
      - name: roar-db
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-pv-claim
      volumes:
      - name: mysql-pv-claim
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      
