apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: roar-new
  labels:
    app: roar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: roar
        version: new
    spec:
      containers:
      - name: roar-web
        image: "localhost:5000/roar-web:v2"
        ports:
        - name: roar-web
          containerPort: 8080
        imagePullPolicy: Always
      - name: roar-db
        image: "localhost:5000/roar-db:v1"
        imagePullPolicy: Always
        env:
        - name: MYSQL_DATABASE
          value: registry
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_ROOT_PASSWORD
          value: root+1
        - name: MYSQL_USER
          value: admin
        ports:
        - containerPort: 3306
          name: roar-db

