apiVersion: v1
kind: Service
metadata:
  name: roar-web
  labels:
    app: roar-web
spec:
  type: NodePort
  ports:
    - name: frontend
      port: 8089
      targetPort: 8080
      nodePort: 30100
  selector:
      app: roar
