apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.deployment.metadata.name }}-current
  labels:
    app: {{ .Values.deployment.metadata.labels.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.spec.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.spec.template.metadata.labels.name }}
        version: current
      annotations: 
        readiness.status.sidecar.istio.io/applicationPorts: ""
    spec:
      containers:
      - name: {{ .Values.deployment.spec.template.spec.containers.web.name }}
        image: "{{ .Values.deployment.spec.template.spec.containers.web.image }}:v1"
        ports:
        - name: roar-web
          containerPort: 8080
        imagePullPolicy: {{ .Values.deployment.spec.template.spec.containers.db.pullPolicy }}
      - name: {{ .Values.deployment.spec.template.spec.containers.db.name }}
        image: "{{ .Values.deployment.spec.template.spec.containers.db.image }}:{{ .Values.deployment.spec.template.spec.containers.db.tag }}"
        imagePullPolicy: {{ .Values.deployment.spec.template.spec.containers.db.pullPolicy }}
        env:
        - name: MYSQL_DATABASE
          value: registry
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_ROOT_PASSWORD
          value: root+1
        - name: MYSQL_USER
          value: admin
        ports:
        - containerPort: {{ .Values.deployment.spec.template.spec.containers.db.ports.containerPort }}
          name: {{ .Values.deployment.spec.template.spec.containers.db.ports.name }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.deployment.metadata.name }}-new
  labels:
    app: {{ .Values.deployment.metadata.labels.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.spec.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.spec.template.metadata.labels.name }}
        version: new
      annotations: 
        readiness.status.sidecar.istio.io/applicationPorts: ""
    spec:
      containers:
      - name: {{ .Values.deployment.spec.template.spec.containers.web.name }}
        image: "{{ .Values.deployment.spec.template.spec.containers.web.image }}:v2"
        ports:
        - name: roar-web
          containerPort: 8080
        imagePullPolicy: {{ .Values.deployment.spec.template.spec.containers.db.pullPolicy }}
      - name: {{ .Values.deployment.spec.template.spec.containers.db.name }}
        image: "{{ .Values.deployment.spec.template.spec.containers.db.image }}:{{ .Values.deployment.spec.template.spec.containers.db.tag }}"
        imagePullPolicy: {{ .Values.deployment.spec.template.spec.containers.db.pullPolicy }}
        env:
        - name: MYSQL_DATABASE
          value: registry
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_ROOT_PASSWORD
          value: root+1
        - name: MYSQL_USER
          value: admin
        ports:
        - containerPort: {{ .Values.deployment.spec.template.spec.containers.db.ports.containerPort }}
          name: {{ .Values.deployment.spec.template.spec.containers.db.ports.name }}

