apiVersion: v1
kind: Service
metadata:
  name: {{ template "roar-chart.name" . }}
  labels:
    app: {{ template "roar-chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.frontendPortName }}
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
      app: {{ .Values.deployment.spec.template.metadata.labels.name }}
     

