apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: roar-web
  labels:
    name: roar-web
  namespace: roar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: roar-web
    spec:
      containers:
      - name: roar-web
        image: localhost:5000/roar-web-v1
        ports:
        - name: web
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: roar-web
  labels:
    name: roar-web
  namespace: roar
spec:
  type: NodePort
  ports:
  - port: 8089
    targetPort: 8080
    nodePort: 31789
  selector:
    name: roar-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql
  namespace: roar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - name: mysql
        image: localhost:5000/roar-db-v1
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: registry
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_ROOT_PASSWORD
          value: root+1
        - name: MYSQL_USER
          value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
  namespace: roar
spec:
  ports:
  - name: "mysql"
    port: 3306
    targetPort: 3306
  selector:
    name: mysql

