# Default values for roar-web chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: localhost:5000/roar-web
  tag: v1
  pullPolicy: Always
deployment:
  ports:
    name: web
    containerPort: 8080
service:
  portType: NodePort
  frontendPortName: frontend
  externalPort: 8080
  internalPort: 8089


